paths:
  raw_data: data/raw/
  processed_data: data/processed/
  models: models/
  reports: reports/

data:
  kaggle_dataset: mexwell/smart-home-energy-consumption
  file_name: smart_home_energy_consumption_large.csv
  target_column: electricity_cost
  datetime_column: timestamp
  frequency: 'H'  # datos por hora

training:
  test_size: 0.15
  random_seed: 42
  epochs: 100
  batch_size: 32

plots:
  tech_blues: [
    "#00FFFF",  # Cyan
    "#00BFFF",  # DeepSkyBlue
    "#1E90FF",  # DodgerBlue
    "#4682B4",  # SteelBlue
    "#5F9EA0",  # CadetBlue
    "#7DF9FF",  # Electric Blue
  ]